.TH gitgraph 1 "2014" "" "User Manual"
.SH NAME
gitgraph \- a git graphs generator
.SH SYNOPSIS
gitgraph \fIDIRECTORY\fR
.SH DESCRIPTION
Scan \fIDIRECTORY\fR for a git repository.
.br
If git repo found then it will draw a graph of contributions on stdout in SVG format.
.SH AUTHOR
Romain Porte <microjoe@mailoo.org>
.SH COPYRIGHT
Copyright (C) 2014  Romain Porte.
.UR http://gnu.org/licenses/agpl.html
License AGPLv3+: GNU Affero GPL version 3 or later
.UE .
.br
This is free software: you are free to change and redistribute it.  There is NO
WARRANTY, to the extent permitted by law.
